name: Docker image builder

on:
  push:
    branches: 
         - main
         - dev
         -  feature*
jobs:
   test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: |
           echo "Branch = test"
           echo "Github Action"
           echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

   if_main:
       runs-on: ubuntu-latest
       if: github.ref == 'refs/heads/main'
       steps:
         - uses: actions/checkout@v2
         - run: |
               echo "Branch = main"
               echo "Github Action"
   name:
     id: check-barnch
     run: |
        if [[ ${{ github.event.ref }} =~ ^refs/heads/feature-[0-9]+$ ]]; then
         echo ::set-output name=match::true
        fi
   if_feature:
       runs-on: ubuntu-latest
       if: steps.check-tag.outputs.match == 'true'
       steps:
         - uses: actions/checkout@v2
         - run: |
               echo "Bramnch = feature"
               echo "Github Action"

       
