name: 'environment resources workflow'
#test
on:
  push:
    branches:
      - dev
      - main

jobs:
  terraform:
    name: 'test ci'
    runs-on: ubuntu-latest

    #    defaults:
    #      run:
    #        shell: bash
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

          # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token

      - name: if main, terraform init, validate, plan, apply
        if: github.event.head_commit.modified == 'Dockerfile'
        run: |
                echo "docker image creation"
