name: Docker image builder

on:
  push:
    branches: 
         - main
         - dev
         -  feature*
jobs:
   test:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'
      steps:
        - uses: actions/checkout@v2
        - run: |
           echo "Branch = test"
           echo "Github Action"
   if_main:
       runs-on: ubuntu-latest
       if: github.ref == 'refs/heads/main'
       steps:
         - uses: actions/checkout@v2
         - run: |
               echo "Branch = main"
               echo "Github Action"
   if_feature:
       runs-on: ubuntu-latest
       if: {{ github.ref == 'refs/heads/feature*' }}
       steps:
         - uses: actions/checkout@v2
         - run: |
               echo "Bramnch = feature"
               echo "Github Action"
       
