name: 'environment resources workflow'
#test
on:
  push:
    branches:
      - dev
      - main

jobs:
  terraform:
    name: 'Terraform-dev'
    runs-on: self-hosted

    defaults:
      run:
        shell: bash
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: if main, terraform init, validate, plan, apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
                terraform version
                #terraform init -input=false
                #terraform plan
                #terraform destroy --auto-approve
