name: 'environment resources workflow'
#test
on:
  push:
    branches:
      - dev
      - main

jobs:
   terraform:
    name: 'terraform iac'
    if: contains(github.event.head_commit.message, 'build-iac')
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: if main, terraform init, validate, plan, apply
        run: |
                echo "iac creation using terrafrom"
   build_image:
    name: 'docker image creation'
    if: contains(github.event.head_commit.message, 'build-image')
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: if main, prod docker image creation
        run: |
                echo "docker image creation"
