name: 'environment resources workflow'
#test
on:
  push:
    branches:
      - dev
      - main

jobs:
  terraform:
    name: 'Terraform-dev'
    runs-on: self-hosted

    defaults:
      run:
        shell: bash
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs docker hello-world
      - name: Hello from Docker
        run: docker run hello-world
