name: 'environment resources workflow'
#test
on:
  push:
    branches:
      - dev
      - main

jobs:
  terraform:
    name: 'test ci'
    runs-on: ubuntu-latest

    #    defaults:
    #      run:
    #        shell: bash
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: if main, terraform init, validate, plan, apply
        if: contains(github.event.head_commit.message, 'smoke_test')
        run: |
                echo "docker image creation"
